global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter
  - job_name: "node_exporter"
    static_configs:
      - targets: ["135.235.136.51:9100"]

  # MySQL Exporter
  - job_name: "mysql_exporter"
    static_configs:
      - targets: ["135.235.136.51:9104"]

  # PostgreSQL Exporter
  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["135.235.136.51:9187"]
